# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firework',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
